services:
  - type: web
    name: productivity-app
    env: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: productivity-app-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://productivity-app.onrender.com

databases:
  - name: productivity-app-db
    plan: free 