services:
  - type: web
    name: productivity-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: productivity-app-db
          property: connectionString
      - key: POSTGRES_PRISMA_URL
        fromDatabase:
          name: productivity-app-db
          property: connectionString
      - key: POSTGRES_URL_NON_POOLING
        fromDatabase:
          name: productivity-app-db
          property: connectionString

databases:
  - name: productivity-app-db
    plan: free
    ipAllowList: [] 