services:
  - type: web
    name: productivity-app
    env: node
    plan: free
    buildCommand: |
      npm install
      npm run migrate:deploy
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: productivity-app-db
          property: connectionString

databases:
  - name: productivity-app-db
    plan: free
    ipAllowList: [] 